language: node_js
node_js:
  - "8"
  - "10"
  
before_install:
  - npm i -g yarn apollo

install:
  - yarn

script:
  - yarn lint
  - yarn test
  - apollo schema:check --key="$APOLLO_TOKEN" --endpoint="http://localhost:4000/graphql"
